download("https://stat.duke.edu/~mc301/data/movies.Rdata", destfile="movies.Rdata")
load("movies.Rdata")
movies$book <- c("no", "yes", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "yes", "yes", "no", "no", "no", "no", "no", "yes", "yes", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "yes", "yes", "no", "no", "no", "no", "yes", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "yes", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "yes", "yes", "no", "no", "no", "no", "no", "yes", "yes", "yes", "no", "yes", "yes", "no", "yes", "yes", "no", "yes", "no", "no", "no", "no", "yes", "yes", "no", "yes", "yes", "no", "no", "no", "no", "no", "yes", "yes", "no", "yes", "yes", "yes", "no", "yes", "no", "no", "no", "no", "no", "yes", "yes", "no", "no", "no", "yes", "no", "yes", "no", "yes", "no", "yes", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "yes", "yes", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "yes", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "yes", "yes", "yes", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "yes", "no", "yes", "no", "yes", "no", "no", "yes", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "yes", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "yes", "yes", "no", "no", "no", "yes", "no", "no", "no", "yes", "no", "no", "no", "yes", "no", "yes", "yes", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "yes", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "yes", "no", "no", "yes", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "yes", "no", "no", "yes", "no", "no", "no", "no", "no", "yes", "no", "no")
movies$mpaa_rating[movies$mpaa_rating == "PG"|movies$mpaa_rating == "G"] = "G"
                                 
#EDA 
plot(movies$audience_score~movies$best_actress_win)
plot(movies$audience_score~movies$best_dir_win)
plot(movies$audience_score~movies$best_actor_win)
plot(movies$audience_score~movies$genre)
plot(movies$audience_score~ movies$runtime)

#inference 
movies$scorecat <- cut(movies$audience_score,c(0,50,96))
barplot(prop.table(table(movies$book,movies$scorecat),1),beside=TRUE,legend=TRUE)
table(movies$book, movies$scorecat)
prop.table(table(movies$book, movies$scorecat),1)
mosaicplot(prop.table(table(movies$book,movies$scorecat),1))
inference(movies$scorecat, movies$book, est="proportion",type="ht",method="theoretical",alternative="twosided",success="(50,96]")

#our regression line
moviead <- lm(audience_score ~ type + genre + runtime + year + mpaa_rating + best_actor_win + best_actress_win + best_dir_win + book, data = movies)
summary(moviead)
movieadnotype <- lm(audience_score ~ genre + runtime + year + mpaa_rating + best_actor_win + best_actress_win + best_dir_win + book, data = movies)
summary(movieadnotype)
movieadnogenre <- lm(audience_score ~ type + runtime + year + mpaa_rating + best_actor_win + best_actress_win + best_dir_win + book, data = movies)
summary(movieadnogenre)
movieadnoruntime <- lm(audience_score ~ type + genre + year + mpaa_rating + best_actor_win + best_actress_win + best_dir_win + book, data = movies)
summary(movieadnoruntime)
movieadnoyear <- lm(audience_score ~ type + genre + runtime + mpaa_rating + best_actor_win + best_actress_win + best_dir_win + book, data = movies)
summary(movieadnoyear)
movieadnompaa <- lm(audience_score ~ type + genre + runtime + year + best_actor_win + best_actress_win + best_dir_win + book, data = movies)
movieadnobestactor <- lm(audience_score ~ type + genre + runtime + year + mpaa_rating + best_actress_win + best_dir_win + book, data = movies)
summary(movieadnobestactor)
movieadnobestactress <- lm(audience_score ~ type + genre + runtime + year + mpaa_rating + best_actor_win + best_dir_win + book, data = movies)
summary(movieadnobestactress)
movieadnobestdirect <- lm(audience_score ~ type + genre + runtime + year + mpaa_rating + best_actor_win + best_actress_win + book, data = movies)
summary(movieadnobestdirect)
movieadnobook <- lm(audience_score ~ type + genre + runtime + year + mpaa_rating + best_actor_win + best_actress_win + best_dir_win, data = movies)
summary(movieadnobook)
movieadnompaatype <- lm(audience_score ~ genre + runtime + year + best_actor_win + best_actress_win + best_dir_win + book, data = movies)
summary(movieadnompaatype)
movieadnompaanogenre <- lm(audience_score ~ type + runtime + year + best_actor_win + best_actress_win + best_dir_win + book, data = movies)
summary(movieadnompaanogenre)
movieadnompaanoruntime <- lm(audience_score ~ type + genre + year + best_actor_win + best_actress_win + best_dir_win + book, data = movies)
summary(movieadnompaanoruntime)
movieadnompaanoyear <- lm(audience_score ~ type + genre + runtime + best_actor_win + best_actress_win + best_dir_win + book, data = movies)
summary(movieadnompaanoyear)
movieadnompaanoactor <- lm(audience_score ~ type + genre + runtime + year + best_actress_win + best_dir_win + book, data = movies)
summary(movieadnompaanoactor)
movieadnompaanoactress <- lm(audience_score ~ type + genre + runtime + year + best_actor_win + best_dir_win + book, data = movies)
summary(movieadnompaanoactress)
movieadnompaanodirect <- lm(audience_score ~ type + genre + runtime + year + best_actor_win + best_actress_win + book, data = movies)
summary(movieadnompaanodirect)
movieadnompaanobook <- lm(audience_score ~ type + genre + runtime + year + best_actor_win + best_actress_win + best_dir_win, data = movies)
summary(movieadnompaanobook)
movieadnompaanobooknotype <- lm(audience_score ~ genre + runtime + year + best_actor_win + best_actress_win + best_dir_win, data = movies)
summary(movieadnompaanobooknotype)
movieadnompaanobooknogenre <- lm(audience_score ~ type + runtime + year + best_actor_win + best_actress_win + best_dir_win, data = movies)
summary(movieadnompaanobooknogenre)
movieadnompaanobooknoruntime <- lm(audience_score ~ type + genre + year + best_actor_win + best_actress_win + best_dir_win, data = movies)
summary(movieadnompaanobooknoruntime)
movieadnompaanobooknoyear <- lm(audience_score ~ type + genre + runtime + best_actor_win + best_actress_win + best_dir_win, data = movies)
summary(movienompaanobooknoyear)
movieadnompaanobooknoactor <- lm(audience_score ~ type + genre + runtime + year + best_actress_win + best_dir_win, data = movies)
summary(movieadnompaanobooknoactor)
movieadnompaanobooknoactress <- lm(audience_score ~ type + genre + runtime + year + best_actor_win + best_dir_win, data = movies)
summary(movieadnompaanobooknoactress)
movieadnompaanobooknodirect <- lm(audience_score ~ type + genre + runtime + year + best_actor_win + best_actress_win, data = movies)
summary(movieadnompaanobooknodirect)
movieadnompaanobooknoactressnotype <- lm(audience_score ~ genre + runtime + year + best_actor_win + best_dir_win, data = movies)
summary(movieadnompaanobooknoactressnotype)
movieadnompaanobooknoactressnogenre <- lm(audience_score ~ type + runtime + year + best_actor_win + best_dir_win, data = movies)
summary(movieadnompaanobooknoactressnogenre)
movieadnompaanobooknoactressnoruntime <- lm(audience_score ~ type + genre + year + best_actor_win + best_dir_win, data = movies)
summary(movieadnompaanobooknoactressnoruntime)
movieadnompaanobooknoactressnoyear <- lm(audience_score ~ type + genre + runtime + best_actor_win + best_dir_win, data = movies)
summary(movieadnompaanobooknoactressnoyear)
movieadnompaanobooknoactressnoactor <- lm(audience_score ~ type + genre + runtime + year + best_dir_win, data = movies)
summary(movieadnompaanobooknoactressnoactor)
movieadnompaanobooknoactressnodirect <- lm(audience_score ~ type + genre + runtime + year + best_actor_win, data = movies)
summary(movieadnompaanobooknoactressnodirect)
mlr <- lm(audience_score ~ genre + runtime + year + best_actor_win + best_dir_win, data = movies)
summary(mlr)
#conditions
plot(mlr)
plot(mlr$residuals~mlr$fitted) #variance check
plot(mlr$residuals~movies$year)
plot(mlr$residuals~movies$best_actor_win)
plot(mlr$residuals~movies$best_dir_win)
plot(mlr$residuals~movies$runtime)
plot(mlr$residuals~movies$genre)
abline(h = 0, lty = 3)
qqnorm(mlr$residuals) #normality check
qqline(mlr$residuals)
hist(mlr$residuals)#normality check
plot(mlr$residuals, xlab='Order of data Collection',ylab='Residuals') #independence check
anova(mlr)
prop.table(table(movies$best_dir_win, movies$best_actor_win)) #colinearity check
plot(movies$runtime~movies$genre) #colinearity check
#colinearity check between genre and type
prop.table(table(movies$genre,movies$type))
prop.table(table(movies$genre,movies$type),1)
prop.table(table(movies$genre,movies$type),2)
plot(movies$audience_score~movies$type)
plot(movies$audience_score~movies$genre)
plot(movies$runtime~movies$type)
plot(movies$year~movies$type)
plot(movies$best_actor_win~movies$type)
plot(movies$best_dir_win~movies$type)
plot(movies$year~movies$genre)
plot(movies$best_actor_win~movies$genre)
prop.table(table(movies$best_actor_win,movies$genre))
prop.table(table(movies$best_actor_win,movies$genre),1)
prop.table(table(movies$best_actor_win,movies$genre),2)
plot(movies$best_dir_win~movies$genre)
prop.table(table(movies$best_dir_win,movies$genre))
prop.table(table(movies$best_dir_win,movies$genre),1)
prop.table(table(movies$best_dir_win,movies$genre),2)
plot(movies$year~movies$runtime)
plot(movies$best_actor_win,movies$runtime)
plot(movies$best_dir_win,movies$runtime)
plot(movies$year~movies$best_actor_win)
plot(movies$year~movies$best_dir_win)


#prediction
furious7 = data.frame(genre="Action & Adventure", runtime=137, year=2015, best_actor_win = "no", best_dir_win = "no")
predict(mlr,furious7,interval="predict")

#best regression line 
brl<-lm(audience_score ~ type+genre+runtime+year+mpaa_rating+imdb_num_votes+critics_score+critics_rating+best_pic_win+top200_box, data = movies)
summary(mlr)
plot(brl$residuals~brl$fitted )
abline(h = 0, lty = 3)
qqnorm(brl$residuals)
qqline(brl$residuals)
hist(brl$residuals)