---
title: "Sta 101 TA Responsibilities"
author: "Dr. Cetinkaya-Rundel & Dr. Windle"
date: "Spring 2015"
output: html_document
---

<br>

### Responsibilities of all TAs:

- **Lab sections:** As a TA your main duty is to lead lab sections. 
    + This course uses R/RStudio. For puposes of this course access RStudio at https://vm-manage.oit.duke.edu/containers using your NetID.
    + Students are expected to create completely reproducible lab reports and projects using RMarkdown/knitr. Prior to the first lab make sure that you are familiar with these tools/packages.
    + Get to lab a few minutes earlier to make sure the instructor computer and projector are working. 
    + Take attendance during the lab sections. You can do this informally (as opposed to calling out names) and use it as an opportunity to get to know your students' names. Print out the team roster for your section and check of names as you interact with each team. (Attendance information will be useful when grading the lab reports.)
    + Flow of lab sections: 
        - 5-10 minutes of introduction to lab and the data set. Make sure students are engaged (not going ahead with the lab on their computers). This introduction should convey the main ideas/skills of the lab.
        - Let students continue with the lab (in teams) while you spend a little bit of time with each team and answer any questions. You should *never* be just sitting behind the instructor computer.
        - From time-to-time address the whole class, making sure teams are progressing roughly at the same rate, and go over any challenging exercises.
        - At the end of the lab for the first few weeks remind the students the deadline and submission instructions.
    + During the lab sections you're also tasked with ensuring smooth and efficient teamwork:
        - If any students are unengaged explicitly ask them to work with their teams.
        - Ask students to change their seating order each week so that each student gets a chance to be in the "middle".
        - Ensure that teams follow the author assignments, and the authors rotate each week.
    + If you must miss a lab, make arrangements for another TA to fill in for you well in advance. <br><br>

- **Problem set & lab grading:** Problem sets and labs must be graded within 6 days of the due date, so that students can review the feedback before submitting the next assigment.
    + Stick closely to the answer key. If you catch an error on the key, or if something is not clear, email the professor and all TAs immediately to resolve the issue. This will save everyone time. If the error is minor, feel free to go in and edit the key directly.
    + On student assignments, note where you take off points, and provide ample *constructive* feedback.
    + If you anticipate not being able to complete the grading by the deadline, bring this to the professor's attention ahead of time so that arrangements can be made. 
    + **Problem sets:** Allowed formats are plain text entry or PDF of typed or handwritten answers. No other formats are allowed. Take off points for any formatting issues especially in PS1 so that the expectations are communicated early on.
    + **Labs:** Only students who were present in the lab session are listed as author/discussant and receive points for the labs. <br><br>

- **Piazza:** All content related course communication must take place on Piazza -- the online discussion forum.
    + Piazza can be accessed via the Sakai site.
    + You will be assigned a TA role on Piazza, which means that your responses will be tagged as such.
    + Adjust your settings so that you're notified when a note is posted on Piazza.
    + Respond to student questions periodically. Do not just give away the answers, instead respond in a way that enables the students to get to the right answer. Don't hesitate to answer a question with a question that helps the student think through the problem. <br><br>

- **Weekly meetings:** During the weekly meetings we will share experiences from the past week and prepare for the following.
    + Each week one TA will present the lab. This presentation should take roughly 5-10 minutes and should be a complete rehearsal of how you plan on presenting the lab to the students. Then, also take a few minutes to discuss any potential difficulties that might arise during the lab. The presenter will also be responsible for either creating or reviewing the key for the week's lab.
    + All TAs must also review the lab (i.e. actually do the entire lab) and come to the meeting with suggestions/questions regarding how best to present the lab to the students.
    + During the meeting you should also be prepared to provide feedback on the past week (what seems to be challenging for students, commonly missed questions on the assignments, questions that commonly come up during office hours, team dynamics, etc.). <br><br>

- **Regrades:** You should only consider regrade requests in the case of errors in tallying points. All other regrade requests must go through the professor -- simply direct the students to the professor. <br><br>

### Responsibilities of the head TAs:
- Ensure that grading is completed by the due date (check a couple days prior and send timely reminders if need be).
- Ensure that answer keys are ready when an assignment is *assigned*.
- Prepare peer evaluations on Qualtrics and compile peer evaluation data (more on this later).
- Review exams and other course material as needed.
    