markdown: kramdown
exclude:
  - LICENSE

layouts: ./_noita
baseurl: /courses/Spring15/sta101.001

noita:
  name: Sta 101 - Data Analysis and Statistical Inference (Spring 2015)
  description: Jekyll theme built with Foundation
  author:
    name: Mine Cetinkaya-Rundel
    url: http://stat.duke.edu/~mc301
    absolute: true
  lang: en
  topbar:
    toggle: Menu
    right:
      - name: Schedule
        url: /
      - name: Info
        url: /info/
      - name: Syllabus
        url: /syllabus/
      - name: Resources
        url: /resources/
      - name: Sakai
        url: https://sakai.duke.edu/portal/site/ba0d1c18-ba55-473f-9d70-b6a1f9559bbe/page/8052e4d1-3af6-425b-bed2-0bc37ab0ef26
        absolute: true
      - name: RStudio
        url: https://vm-manage.oit.duke.edu/containers
        absolute: true
      - name: Links
        url: /links/
      - name: FAQ
        url: /faq/
